### stable features ###

max_width = 100

normalize_comments   = true
reorder_imports      = true
use_try_shorthand    = true
wrap_comments        = true

### unstable features ##

unstable_features = true

struct_field_align_threshold = 64
use_small_heuristics = "Max"
